### ISSUE TITLE
Remove outdated comments 

### ISSUE THREAD

**Issue by technic** [acampb/azuredevops-psscriptanalyzer-prcomments#2]
Hi,
Thanks for tutorial in your blog post.

What happen with the old comments when the new code with a fix is pushed to the PR? Will outdated comments automatically resolve or deleted?

**Comment by acampb** [comment]
Hi @technic - The code to add a Pull Request comment only adds new comments so it will not resolve or delete previous comments. I would suggest a user manually resolve the PR comments when they fix issues discovered by PSScriptAnalyzer.

**Comment by technic** [comment]
Ok. Thanks for the answer.
